on:
  push:
    branches: ["dev", "feature/github-actions-test"]

env:
  # GitHub repository name
  REPO_NAME: elective-web-auth
  # Database configuration
  DB_NAME: testdb
  DB_USER: user
  DB_PASS: pass
  DB_PORT: 3306

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run unit tests
        run: docker run -e NODE_ENV_PROFILE=test -e DB_NAME=${{ env.DB_NAME }} -e DB_USER=${{ env.DB_USER }} -e DB_PASS=${{ env.DB_PASS }} ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }} npm run test

      # - name: Push Docker image
      # run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}
