on:
  push:
    branches: ["dev", "feature/github-actions-test"]

env:
  # GitHub repository name
  REPO_NAME: elective-web-auth

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }} .

      - name: Run unit tests
        run: docker run -e NODE_ENV_PROFILE=test ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }} npm run test

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   if: success()
      # run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}
